//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_LOG
    {
        public int ID_LOG { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string ACTIVITY_TYPE { get; set; }
        public string DETAIL { get; set; }
        public Nullable<System.DateTime> DATE_ACTIVITY { get; set; }
    
        public virtual USERAPP USERAPP { get; set; }
    }
}
