//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int ID { get; set; }
        public string DETAIL { get; set; }
        public string STREET { get; set; }
        public string WARD { get; set; }
        public string DISTRICT { get; set; }
        public string IDPERSON { get; set; }
    
        public virtual PERSONINFOR PERSONINFOR { get; set; }
    }
}
