//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_IN
    {
        public string ID_BILL { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public Nullable<int> IDDOG { get; set; }
        public Nullable<System.DateTime> DAY_BILL { get; set; }
        public Nullable<long> FINE { get; set; }
    
        public virtual USERAPP USERAPP { get; set; }
        public virtual DOG DOG { get; set; }
    }
}
