//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHBOOK
    {
        public int ID { get; set; }
        public Nullable<long> VALUE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> ID_USER { get; set; }
        public string DESTRIPTION { get; set; }
    
        public virtual USERAPP USERAPP { get; set; }
    }
}
