//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOG()
        {
            this.BILL_IN = new HashSet<BILL_IN>();
            this.BILL_OUT = new HashSet<BILL_OUT>();
            this.DOG_DESTROY = new HashSet<DOG_DESTROY>();
            this.DOG_INFOR = new HashSet<DOG_INFOR>();
        }
    
        public Nullable<double> WEIGHT { get; set; }
        public int ID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<System.DateTime> DAYIN { get; set; }
        public Nullable<long> FOODPRICE { get; set; }
        public string IDDOGHOUSE { get; set; }
        public Nullable<bool> DETROYED { get; set; }
        public byte[] IMAGES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_IN> BILL_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_OUT> BILL_OUT { get; set; }
        public virtual DOGHOUSE DOGHOUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOG_DESTROY> DOG_DESTROY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOG_INFOR> DOG_INFOR { get; set; }
    }
}
