//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOG_INFOR
    {
        public int ID { get; set; }
        public string STREET { get; set; }
        public string WARD { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<System.TimeSpan> TIME { get; set; }
        public Nullable<int> IDDOG { get; set; }
    
        public virtual DOG DOG { get; set; }
    }
}
