//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERAPP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERAPP()
        {
            this.ACCOUNTs = new HashSet<ACCOUNT>();
            this.ACTIVITY_LOG = new HashSet<ACTIVITY_LOG>();
            this.BILL_IN = new HashSet<BILL_IN>();
            this.BILL_OUT = new HashSet<BILL_OUT>();
            this.CASHBOOKs = new HashSet<CASHBOOK>();
            this.DOG_DESTROY = new HashSet<DOG_DESTROY>();
            this.PAYMENT_RECEIPT_VOUCHER = new HashSet<PAYMENT_RECEIPT_VOUCHER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDPERSON { get; set; }
        public Nullable<int> SALARY { get; set; }
        public Nullable<System.DateTime> DAYJOIN { get; set; }
        public string ID_BANK { get; set; }
        public string ID_MEDICAL { get; set; }
        public byte[] IMAGES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVITY_LOG> ACTIVITY_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_IN> BILL_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_OUT> BILL_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASHBOOK> CASHBOOKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOG_DESTROY> DOG_DESTROY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAYMENT_RECEIPT_VOUCHER> PAYMENT_RECEIPT_VOUCHER { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
