CREATE DATABASE DOGMANAGED
GO
USE DOGMANAGED

GO

CREATE TABLE PERSON
(
	ID INT PRIMARY KEY,
	NOTE NVARCHAR(MAX)
)
GO

CREATE TABLE DOGHOUSE
(
	ID  NVARCHAR(10) PRIMARY KEY,
	DESTRIPTION VARCHAR(100)
)
alter table doghouse alter column DESTRIPTION nvarchar(max) 
GO
CREATE TABLE PERSONINFOR
(
	ID_TT VARCHAR(10) PRIMARY KEY, -- CMND
	ID INT FOREIGN KEY REFERENCES dbo.PERSON(ID),
	NAME NVARCHAR(100),
	EMAIL NVARCHAR(100),
	PHONE VARCHAR(20),
	BIRHDAY DATE,
	gender NVARCHAR default N'Nữ'
	
)
GO
alter table PERSONINFOR ALTER COLUMN GENDER NVARCHAR(10)
go
CREATE TABLE ADDRESS
(
	ID INT PRIMARY KEY IDENTITY,
	DETAIL NVARCHAR (20), -- MÔ TẢ 
	STREET NVARCHAR(50),
	WARD VARCHAR(50),
	DISTRICT NVARCHAR(50),
	IDPERSON VARCHAR(10) FOREIGN KEY REFERENCES dbo.PERSONINFOR(ID_TT)
)
GO
CREATE TABLE DOGTYPE
(
	ID_TYPE VARCHAR(10) PRIMARY KEY,
	NAME_TYPE NVARCHAR(50) 
)
GO
CREATE TABLE DOG
(
	WEIGHT FLOAT,
	ID INT IDENTITY PRIMARY KEY, 
	TYPE VARCHAR(10) REFERENCES  DOGTYPE(ID_TYPE), 	
	DAYIN DATE,
	FOODPRICE BIGINT,
	IDDOGHOUSE NVARCHAR(10) FOREIGN KEY REFERENCES dbo.DOGHOUSE(ID),
	DETROYED BIT DEFAULT 0, --1 DETROYED, 0 NOT
	IMAGES VARBINARY(MAX)

)
ALTER TABLE DOG ADD STATUS INT -- 0 ĐANG GIAM GIỮ, 1 ĐÃ TRẢ
GO
CREATE TABLE DOG_INFOR -- THÔNG TIN BẮT CHÓ
(
	ID INT PRIMARY KEY IDENTITY,	
	STREET NVARCHAR(50),
	WARD VARCHAR(50),
	DISTRICT NVARCHAR(50),
	TIME TIME, -- TOI GIAN BAT CHO
	IDDOG INT FOREIGN KEY REFERENCES dbo.DOG(ID)

)
GO

CREATE TABLE USERAPP
(
	ID INT IDENTITY PRIMARY KEY,
	IDPERSON INT FOREIGN KEY REFERENCES dbo.PERSON(ID),
	SALARY INT, 
	DAYJOIN DATE,
	ID_BANK VARCHAR(20),
	ID_MEDICAL VARCHAR(20),
	IMAGES VARBINARY(MAX)
)
GO
GO

CREATE TABLE CUSTOMER
(
	ID INT PRIMARY KEY IDENTITY,
	IDPERSON INT FOREIGN KEY REFERENCES dbo.PERSON(ID)
)
GO
CREATE TABLE ACCOUNT
(
	ID_USER INT FOREIGN KEY REFERENCES dbo.USERAPP(ID),
	USERNAME VARCHAR(50) PRIMARY KEY,
	PASSWORD VARCHAR(100),
	PASSWORD2 VARCHAR(100),
	TYPE INT DEFAULT 0,
	ISBAN BIT DEFAULT 0
)
GO
GO
CREATE TABLE BILL_OUT
(
	ID_BILL VARCHAR(10) PRIMARY KEY ,
	ID_USER INT FOREIGN KEY REFERENCES dbo.USERAPP(ID),
	ID_CUSTOMER INT FOREIGN KEY REFERENCES dbo.CUSTOMER(ID),
	IDDOG INT FOREIGN KEY REFERENCES dbo.DOG(ID),
	DAY_BILL DATE,
	FINE BIGINT, -- TIỀN PHẠT
	TOTALPRICE BIGINT -- TỔNG TIỀN PHẠT 

)
go

CREATE TABLE BILL_IN
(
	ID_BILL VARCHAR(10) PRIMARY KEY ,
	ID_USER INT FOREIGN KEY REFERENCES dbo.USERAPP(ID),
	IDDOG INT FOREIGN KEY REFERENCES dbo.DOG(ID),
	DAY_BILL DATE,
	FINE BIGINT -- TIỀN PHẠT 	
)
GO

CREATE TABLE ACTIVITY_LOG
(
	ID_LOG INT PRIMARY KEY IDENTITY,
	ID_USER INT FOREIGN KEY REFERENCES dbo.USERAPP(ID),
	ACTIVITY_TYPE NVARCHAR(100),
	DETAIL NVARCHAR (MAX),
	DATE_ACTIVITY DATE

)
GO
CREATE TABLE DOG_DESTROY
(
	ID INT PRIMARY KEY IDENTITY,
	IDDOG INT FOREIGN KEY REFERENCES DOG(id),
	ID_USER INT FOREIGN KEY REFERENCES dbo.USERAPP(ID), -- MÃ NGƯỜI HỦY
	DATE_DESTROY DATE
	
)
GO

CREATE TABLE PAYMENT_RECEIPT_VOUCHER -- PHIẾU THU, CHI
(
	ID INT PRIMARY KEY IDENTITY,
	DATETIME DATETIME,
	TYPE BIT DEFAULT 0, --1 THU, 0 CHI
	VALUE BIGINT, -- SỐ TIÊN
	DESTRIPTION NVARCHAR(MAX)  NULL,
	ID_USER INT FOREIGN KEY REFERENCES dbo.USERAPP(ID), -- MÃ NGƯỜI LẬP PHIẾU
	
)
GO
CREATE TABLE CASHBOOK
(
	ID INT PRIMARY KEY IDENTITY,
	VALUE BIGINT, -- TỒN QUỸ
	DATE DATE, --NGÀY LƯU
	ID_USER INT FOREIGN KEY REFERENCES dbo.USERAPP(ID), -- MÃ NGƯỜI LƯU QUỸ
	DESTRIPTION NVARCHAR(MAX) -- MÔ TẢ
)
GO
--------------------INSERT SOME TEST DATA
GO
INSERT PERSON VALUES (001, N'ADMIN CỦA HỆ THỐNG')
INSERT PERSON VALUES (002, N'NHÂN VIÊN')
INSERT PERSON VALUES (003, N'KẾ TOÁN')
GO
INSERT PERSONINFOR VALUES ('281157576',1,N'Nguyễn Phi Cường','nficuong@gmail.com', '01638406801', '05/05/1997', N'Nam')
INSERT PERSONINFOR VALUES ('223123133',2,N'Đỗ Thị Thanh Huệ','thanhhueqng@gmail.com', '0987676562', '01/03/1997', N'Nữ')
INSERT PERSONINFOR VALUES ('241665442',3,N'Nguyễn Thị Ngọc','ntngoc.itus@gmail.com', '0168343121', '12/08/1997', N'Nữ')
go
INSERT ADDRESS VALUES (N'',N'976 Đường 3/2', N'P.3', N'Quận 11', '281157576')
INSERT ADDRESS VALUES (N'',N'24/6 Nguyễn Thị Nhỏ', N'P.8', N'Quận 10', '223123133')
INSERT ADDRESS VALUES (N'',N'678 Âu Cơ', N'P.2', N'Q.Tân Phú', '241665442')

go
INSERT USERAPP VALUES (1,15000000, '05/05/2015','9871232341276','YT78463516', NULL)
INSERT USERAPP VALUES (2,10000000, '03/12/2013','1234133124412','YT12233313', NULL)
INSERT USERAPP VALUES (3,15000000, '05/05/2015','6432452521231','YT09432224', NULL)
go
 INSERT ACCOUNT VALUES (2, 'admin','admin','123',0,0)
 INSERT ACCOUNT VALUES (3, 'hue','hue','456',0,0)
 INSERT ACCOUNT VALUES (4, 'ngoc','ngoc','789',0,0)

 ---======================================================================

go
insert DOGHOUSE VALUES ('DH01','Chuồng chó 1')
insert DOGHOUSE VALUES ('DH02','Chuồng chó 2')
insert DOGHOUSE VALUES ('DH03','Chuồng chó 3')

go
insert DOGTYPE values ('DTYPE_1', 'Chó thường VN')
insert DOGTYPE values ('DTYPE_2', 'Chó cảnh VN')
insert DOGTYPE values ('DTYPE_3', 'Chó ngoại loại 1')
go
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (5.5, 'DTYPE_1','01/04/2018',20000,'DH01',0)
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (6.5, 'DTYPE_2','02/02/2018',15000,'DH03',0)
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (15.5, 'DTYPE_1','11/08/2018',28000,'DH01',0)
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (8, 'DTYPE_3','09/12/2018',7500,'DH02',0)
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (2.2, 'DTYPE_2','12/06/2018',11000,'DH02',0)
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (6, 'DTYPE_3','12/12/2018',9500,'DH03',0)
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (14, 'DTYPE_1','02/07/2018',18500,'DH01',0)
INSERT DOG (WEIGHT,TYPE,DAYIN,FOODPRICE,IDDOGHOUSE) VALUES (7.2, 'DTYPE_1','07/23/2018',30000,'DH01',0)
go
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'92/2 Âu cơ','2',N'Tân Phú', '13:00:00',1)
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'121/6/2 Trường Chinh','3',N'Tân Bình', '5:30:00',2)
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'203 Cộng Hòa','3',N'Q12', '15:10:00',3)
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'69/2 Lạc Long Quân','6',N'Tân Phú', '8:20:00',4)
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'1002/12 Đường 3tháng 5','9',N'Q11', '14:10:00',5)
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'79/2 Ngô Quyền','An Lập',N'Q10', '8:45:00',6)
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'212/4 Hòa hảo','8',N'Q10', '16:50:00',7)
INSERT DOG_INFOR (STREET,WARD,DISTRICT,TIME,IDDOG) VALUES(N'224 Nguyễn Văn Cừ','10',N'Q5', '12:30:00',9)

